### ISSUE TITLE
Can't test after trainning imagenet

### ISSUE THREAD

**Issue by trinh-hoang-hiep** [DoubleClass/GMM#6]
I have a problem with the get_data function in clip_base/dataset.py line 70 giving an error that folder "/imagenet-r/test" does not exist. 

Traceback (most recent call last):
  File "/home/thhiep/dataspeech/voice_conversion/GMM/batch_eval.py", line 94, in <module>
    eval_dataset, classes_names = build_cl_scenarios(
  File "/home/thhiep/dataspeech/voice_conversion/GMM/clip_base/datasets.py", line 167, in build_cl_scenarios
    scenario = ClassIncremental(
  File "/home/thhiep/anaconda3/envs/GMM/lib/python3.9/site-packages/continuum/scenarios/class_incremental.py", line 45, in __init__
    self._nb_tasks = self._setup(nb_tasks)
  File "/home/thhiep/anaconda3/envs/GMM/lib/python3.9/site-packages/continuum/scenarios/class_incremental.py", line 49, in _setup
    x, y, _ = self.cl_dataset.get_data()
  File "/home/thhiep/dataspeech/voice_conversion/GMM/clip_base/datasets.py", line 71, in get_data
    return super().get_data()
  File "/home/thhiep/anaconda3/envs/GMM/lib/python3.9/site-packages/continuum/datasets/base.py", line 465, in get_data
    self.dataset = torchdata.ImageFolder(self.data_path)
  File "/home/thhiep/anaconda3/envs/GMM/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 309, in __init__
    super().__init__(
  File "/home/thhiep/anaconda3/envs/GMM/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 144, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/home/thhiep/anaconda3/envs/GMM/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 218, in find_classes
    return find_classes(directory)
  File "/home/thhiep/anaconda3/envs/GMM/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 40, in find_classes
    classes = sorted(entry.name for entry in os.scandir(directory) if entry.is_dir())
FileNotFoundError: [Errno 2] No such file or directory: '/home/thhiep/dataspeech/voice_conversion/GMM/imagenet-r/test'

**Comment by DoubleClass** [comment]
make sure you extract the packed datasets and the folder exist:
![image](https://github.com/DoubleClass/GMM/assets/35952616/8df602a0-a624-483d-a9c6-dcd62a45cf36)

**Comment by trinh-hoang-hiep** [comment]
Thank you for your quick support, I missed putting it in the 'test' folder, I fixed it and it worked, Thank you very much for your great work
